# Generated by Django 4.0.4 on 2022-04-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
